name: Build Docker and push to registry (Django)
on:
  push:
    branch:
      - 'main'
      - 'staging'
  release:
    types: [published, created, edited]
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3.0.0
      -
        name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v3.7.0
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ github.repository_owner }}/e-uscito-joypad-db
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{row}}
            type=sha
      -
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
      -
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
      -
        name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push Docker images
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./euscitojoypad_db/
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
